version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
      codeql-all:
        patterns:
          - 'github/codeql-action/*'
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      eslint-major:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-*'
          - '@typescript-eslint/*'
        update-types:
          - major
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
    cooldown:
      default-days: 7
