name: 'TestSpace Project Creation'
description: 'Create a TestSpace Project'
author: 'fletort'

inputs:
  repository:
    description:
      'Repository name with owner. For example, fletort/testspace-create-action'
    default: ${{ github.repository }}
  token:
    description: >
      Personal testspace token used to interact with the testspace API to create
      the project.
    required: true
  domain:
    description: >
      Testspace SubDomain
    default: ${{ github.repository_owner }}

outputs:
  id:
    description: 'Id of the created testspace project.'
  name:
    description: 'Name of the created testspace project.'

runs:
  using: node20
  main: dist/index.js
