name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Init Initial Integration Test Context
        id: test-context
        run: __tests__/integration-test-init.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

      - name: Test Local Action On a new Project
        id: test-action-new
        uses: ./
        with:
          token: ${{ secrets.TESTSPACE_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ env.PROJECT_NAME }}

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action-new.outputs.id }} - ${{steps.test-action-new.outputs.name }}"

      - name: Test Local Action on an existing Project
        id: test-action-existing
        uses: ./
        with:
          token: ${{ secrets.TESTSPACE_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ env.PROJECT_NAME }}

      - name: Check Than TestSpace project is the same
        run: |
          if [[ ${{ steps.test-action-new.outputs.id }} == ${{steps.test-action-existing.outputs.id }} ]]; then
            exit 0
          else
            exit 1
          fi

      - name: Clean Test Data
        if: always()
        run: __tests__/integration-test-clean.sh
        env:
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}
          TESTSPACE_PROJECT_ID: ${{ steps.test-action-new.outputs.id }}
